packages:
  - apps/*
  - packages/**
  - tooling/*
  - scripts

catalog:
  '@tanstack/devtools-vite': ^0.5.1
  '@tanstack/react-devtools': ^0.9.5
  '@tanstack/react-form': ^1.28.2
  '@tanstack/react-query': ^5.90.21
  '@tanstack/react-query-devtools': ^5.91.3
  '@tanstack/react-router': ^1.159.10
  '@tanstack/react-router-devtools': ^1.159.10
  '@tanstack/react-start': ^1.159.11
  '@types/fs-extra': ^11.0.4
  '@types/lodash-es': ^4.17.12
  '@types/node': 24.10.4
  '@vitejs/plugin-react': ^5.1.4
  babel-plugin-react-compiler: ^1.0.0
  fs-extra: ^11.3.3
  jiti: ^2.6.1
  lodash-es: ^4.17.23
  nitro: 3.0.1-alpha.2
  rimraf: ^6.1.2
  superjson: ^2.2.6
  tsdown: ^0.20.3
  tw-animate-css: ^1.4.0
  type-fest: ^5.4.4
  typescript: ^5.9.3
  vite: ^8.0.0-beta.14
  vite-tsconfig-paths: ^6.1.1
  vitest: ^4.0.18
  zod: ^4.3.6

catalogs:
  react19:
    '@types/react': ^19.2.14
    '@types/react-dom': ^19.2.3
    react: ^19.2.4
    react-dom: ^19.2.4
  tailwindv4:
    '@tailwindcss/vite': ^4.1.18
    tailwindcss: ^4.1.18
