packages:
  - apps/*
  - packages/*

catalog:
  '@tanstack/react-form': ^1.28.0
  '@types/node': ^25.2.0
  '@types/react': ^19.2.10
  '@types/react-dom': ^19.2.3
  '@vitest/coverage-v8': ^4.0.18
  '@vitest/ui': ^4.0.18
  better-auth: ^1.4.18
  jsdom: ^28.0.0
  next: ^16.1.6
  react: ^19.2.4
  react-dom: ^19.2.4
  shadcn: ^3.8.2
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  vite-tsconfig-paths: ^6.0.5
  vitest: ^4.0.18
  zod: ^4.3.6
