packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@tailwindcss/vite": "^4.1.18"
  "@tanstack/react-router": "^1.157.16"
  "@tanstack/react-start": "^1.157.16"
  "@types/react": "^19.2.10"
  "@types/react-dom": "^19.2.3"
  "@vitejs/plugin-react": "^5.1.2"
  "@vitest/coverage-v8": "^4.0.18"
  "@vitest/ui": "^4.0.18"
  better-auth: "^1.4.17"
  jsdom: "^27.4.0"
  nitro: "3.0.1-alpha.2"
  react: "^19.2.4"
  react-dom: "^19.2.4"
  shadcn: "^3.7.0"
  tailwind-merge: "^3.4.0"
  tailwindcss: "^4.1.18"
  tw-animate-css: "^1.4.0"
  typescript: "^5.9.3"
  vite: "8.0.0-beta.10"
  vite-tsconfig-paths: "^6.0.5"
  vitest: "^4.0.18"
  zod: "^4.3.6"
