packages:
  - apps/*
  - packages/*

catalog:
  '@tailwindcss/vite': ^4.1.18
  '@tanstack/react-router': ^1.154.8
  '@tanstack/react-start': ^1.154.8
  '@testing-library/react': ^16.3.2
  '@types/react': ^19.2.9
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.2
  '@vitest/coverage-v8': ^4.0.17
  '@vitest/ui': ^4.0.17
  better-auth: ^1.4.16
  jsdom: ^27.4.0
  nitro: 3.0.1-alpha.2
  react: ^19.2.3
  react-dom: ^19.2.3
  shadcn: ^3.6.3
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  vite: ^8.0.0-beta.8
  vite-tsconfig-paths: ^6.0.4
  vitest: ^4.0.17
  zod: ^4.3.5
