packages:
  - apps/*
  - packages/**
  - tooling/*
  - scripts

catalog:
  '@hookform/resolvers': 5.2.2
  '@tanstack/react-query': ^5.90.5
  '@tanstack/react-router': ^1.133.22
  '@tanstack/react-router-ssr-query': ^1.133.22
  '@tanstack/react-start': ^1.133.22
  '@types/node': ~24.9.1
  cross-env: ^10.1.0
  date-fns: ^4.1.0
  dotenv-cli: ^10.0.0
  drizzle-orm: ^0.44.6
  drizzle-zod: ^0.8.3
  fast-glob: ^3.3.3
  fs-extra: ^11.3.2
  jiti: ^2.6.1
  lodash-es: ^4.17.21
  lucide-react: ^0.546.0
  nitro: ^3.0.1-alpha.0
  react-hook-form: 7.65.0
  rimraf: ^6.0.1
  superjson: ^2.2.3
  type-fest: ^5.1.0
  vite: ^7.1.12
  vitest: ^4.0.1
  zod: ^4.1.12
  zustand: ^5.0.8

catalogs:
  dev:
    '@biomejs/biome': ^2.2.7
    lefthook: ^2.0.0
    typescript: ~5.9.3
  react19:
    '@types/react': ^19.2.2
    '@types/react-dom': ^19.2.2
    react: ^19.2.0
    react-dom: ^19.2.0
  tailwindv4:
    '@tailwindcss/postcss': ^4.1.16
    tailwindcss: ^4.1.16

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - lefthook
  - sharp

overrides:
  esbuild: 0.25.11

publicHoistPattern:
  - '*prettier*'
