/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmailRouteRouteImport } from './routes/email/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailSplatRouteImport } from './routes/email/$'
import { Route as ApiSourceRouteImport } from './routes/api/source'
import { Route as ApiSendRouteImport } from './routes/api/send'
import { Route as ApiRenderRouteImport } from './routes/api/render'

const EmailRouteRoute = EmailRouteRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailSplatRoute = EmailSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => EmailRouteRoute,
} as any)
const ApiSourceRoute = ApiSourceRouteImport.update({
  id: '/api/source',
  path: '/api/source',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendRoute = ApiSendRouteImport.update({
  id: '/api/send',
  path: '/api/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRenderRoute = ApiRenderRouteImport.update({
  id: '/api/render',
  path: '/api/render',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/email': typeof EmailRouteRouteWithChildren
  '/api/render': typeof ApiRenderRoute
  '/api/send': typeof ApiSendRoute
  '/api/source': typeof ApiSourceRoute
  '/email/$': typeof EmailSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/email': typeof EmailRouteRouteWithChildren
  '/api/render': typeof ApiRenderRoute
  '/api/send': typeof ApiSendRoute
  '/api/source': typeof ApiSourceRoute
  '/email/$': typeof EmailSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/email': typeof EmailRouteRouteWithChildren
  '/api/render': typeof ApiRenderRoute
  '/api/send': typeof ApiSendRoute
  '/api/source': typeof ApiSourceRoute
  '/email/$': typeof EmailSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/email'
    | '/api/render'
    | '/api/send'
    | '/api/source'
    | '/email/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/email' | '/api/render' | '/api/send' | '/api/source' | '/email/$'
  id:
    | '__root__'
    | '/'
    | '/email'
    | '/api/render'
    | '/api/send'
    | '/api/source'
    | '/email/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmailRouteRoute: typeof EmailRouteRouteWithChildren
  ApiRenderRoute: typeof ApiRenderRoute
  ApiSendRoute: typeof ApiSendRoute
  ApiSourceRoute: typeof ApiSourceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/$': {
      id: '/email/$'
      path: '/$'
      fullPath: '/email/$'
      preLoaderRoute: typeof EmailSplatRouteImport
      parentRoute: typeof EmailRouteRoute
    }
    '/api/source': {
      id: '/api/source'
      path: '/api/source'
      fullPath: '/api/source'
      preLoaderRoute: typeof ApiSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send': {
      id: '/api/send'
      path: '/api/send'
      fullPath: '/api/send'
      preLoaderRoute: typeof ApiSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/render': {
      id: '/api/render'
      path: '/api/render'
      fullPath: '/api/render'
      preLoaderRoute: typeof ApiRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EmailRouteRouteChildren {
  EmailSplatRoute: typeof EmailSplatRoute
}

const EmailRouteRouteChildren: EmailRouteRouteChildren = {
  EmailSplatRoute: EmailSplatRoute,
}

const EmailRouteRouteWithChildren = EmailRouteRoute._addFileChildren(
  EmailRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmailRouteRoute: EmailRouteRouteWithChildren,
  ApiRenderRoute: ApiRenderRoute,
  ApiSendRoute: ApiSendRoute,
  ApiSourceRoute: ApiSourceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
